version: v2beta1

vars:
  ANTHROPIC_API_KEY:
    source: input
    question: "Enter your Anthropic API key:"

images:
  claude-agent:
    image: claude-agent
    dockerfile: Dockerfile
    context: .

hooks:
  - name: create-anthropic-secret
    events: ["before:deploy", "before:dev"]
    command: |-
      if [ -z "${ANTHROPIC_API_KEY}" ]; then
        echo "Error: ANTHROPIC_API_KEY is required"
        exit 1
      fi
      echo "Creating claude-code-secrets..."
      kubectl create secret generic claude-code-secrets \
        --from-literal=api-key="${ANTHROPIC_API_KEY}" \
        --dry-run=client -o yaml | kubectl apply -f -

pipelines:
  deploy: |-
    build_images --all
    create_deployments --all

  dev: |-
    build_images --all
    create_deployments --all
    start_dev --all

# Ark example profile - enables DinD for Kind clusters. See examples/ark/
# Usage: devspace dev -p ark
profiles:
  - name: ark
    patches:
      - op: add
        path: deployments.claude-agent.helm.values.env.DOCKER_HOST
        value: tcp://localhost:2375
      - op: add
        path: deployments.claude-agent.helm.values.extraContainers
        value:
          - name: dind
            image: docker:dind
            securityContext:
              privileged: true
            volumeMounts:
              - name: dind-storage
                mountPath: /var/lib/docker
      - op: add
        path: deployments.claude-agent.helm.values.extraVolumes
        value:
          - name: dind-storage
            emptyDir: {}

deployments:
  claude-agent:
    helm:
      chart:
        name: ./chart
      values:
        image:
          repository: claude-agent
        apiKeySecret: claude-code-secrets

dev:
  claude-agent:
    imageSelector: claude-agent
    # Container to target when multiple containers exist (e.g., ark profile adds dind sidecar)
    container: claude-code-agent

    # Use the actual image (has docker, kubectl, etc.) - no devImage replacement
    command:
      - sh
      - -c
      - |
        cd /app
        npm install
        # Copy ark example claude config (CLAUDE.md + skills)
        cp -r /app/examples/ark/claude/* ~/.claude/ 2>/dev/null || true
        npm run dev
    logs:
      lastLines: 50
    sync:
      - path: .:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
