version: v2beta1

vars:
  ANTHROPIC_API_KEY:
    source: input
    question: "Enter your Anthropic API key:"

images:
  claude-agent:
    image: claude-agent
    dockerfile: Dockerfile
    context: .

pipelines:
  deploy: |-
    build_images --all
    create_deployments --all

  dev: |-
    build_images --all
    create_deployments --all
    start_dev --all

deployments:
  claude-agent:
    helm:
      chart:
        name: ./chart
      values:
        image:
          repository: claude-agent
        apiKey: ${ANTHROPIC_API_KEY}

dev:
  claude-agent:
    imageSelector: claude-agent
    container: claude-code-agent
    command:
      - sh
      - -c
      - |
        cd /app
        npm install
        npm run dev
    logs:
      lastLines: 50
    sync:
      - path: .:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
