version: v2beta1

# Uses pre-built base image from Docker Hub. If missing, run from repo root:
#   make docker-push-base

vars:
  ANTHROPIC_API_KEY:
    source: input
    question: "Enter your Anthropic API key:"
  GH_TOKEN:
    source: input
    question: "Enter your GitHub token (or run 'gh auth token'):"

hooks:
  - name: create-configmaps
    events: ["before:deploy", "before:dev"]
    command: |-
      echo "Creating ConfigMaps for Claude config..."
      kubectl create configmap ark-mcp-config --from-file=mcp-config.json -o yaml --dry-run=client | kubectl apply -f -

pipelines:
  deploy: |-
    create_deployments --all

  dev: |-
    create_deployments --all
    start_dev --all

deployments:
  claude-agent:
    helm:
      chart:
        name: ../../chart
      valuesFiles:
        - values.yaml
      values:
        image:
          repository: dwmkerr/claude-code-agent-base
          tag: 0.1.1-rc6
        apiKey: ${ANTHROPIC_API_KEY}
        env:
          GH_TOKEN: "${GH_TOKEN}"
        # Override: don't use ConfigMaps in dev mode, devspace syncs files directly
        claude:
          claudeDefaultsConfigMap: ""
          skills: []

dev:
  claude-agent:
    labelSelector:
      app.kubernetes.io/name: claude-code-agent
    devImage: dwmkerr/claude-code-agent-base:0.1.1-rc6
    container: claude-code-agent
    command:
      - sh
      - -c
      - |
        cd /app
        npm install
        npx tsx watch src/main.ts --claude-defaults-dir /home/claude-code-agent/.claude-defaults -- --mcp-config /config/mcp-config.json --dangerously-skip-permissions
    logs:
      lastLines: 50
    sync:
      - path: ../..:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
      # Sync workspace bidirectionally - screenshots and files sync back to local
      - path: ./workspace:/workspace
        disableDownload: false
        excludePaths:
          - "**/.git"
          - "**/node_modules"
          - "**/.devspace"
          - "**/dist"
          - "**/__pycache__"
      # Sync claude-defaults (CLAUDE.md, skills) - copied to ~/.claude/ on startup
      - path: ./claude-defaults:/home/claude-code-agent/.claude-defaults
        disableDownload: true
